services:
    ernadoo.phpbbdirectory.cron.task.core.prune_categorie:
        class: ernadoo\phpbbdirectory\cron\task\core\prune_categorie
        arguments:
            - '@config'
            - '@ernadoo.phpbbdirectory.core.cron'
        calls:
            - [set_name, [ernadoo.phpbbdirectory.cron.task.core.prune_categorie]]
        tags:
            - { name: cron.task }