imports:
    - { resource: cron_tasks.yml }
    - { resource: notifications.yml }
    - { resource: tables.yml }

services:
    ernadoo.phpbbdirectory.controller.acp.main:
        class: ernadoo\phpbbdirectory\controller\acp\main
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'

    ernadoo.phpbbdirectory.controller.acp.cat:
        class: ernadoo\phpbbdirectory\controller\acp\cat
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@cache'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@ernadoo.phpbbdirectory.core.categorie'
            - '@ernadoo.phpbbdirectory.core.nestedset_category'

    ernadoo.phpbbdirectory.controller.acp.settings:
        class: ernadoo\phpbbdirectory\controller\acp\settings
        autowire: true

    ernadoo.phpbbdirectory.controller.acp.validation:
        class: ernadoo\phpbbdirectory\controller\acp\validation
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@pagination'
            - '@language'
            - '@log'
            - '@notification_manager'
            - '@request'
            - '@template'
            - '@user'
            - '@ernadoo.phpbbdirectory.core.categorie'
            - '@ernadoo.phpbbdirectory.core.link'
            - '%core.root_path%'
            - '%core.php_ext%'

    ernadoo.phpbbdirectory.controller.categories:
        class: ernadoo\phpbbdirectory\controller\categories
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@request'
            - '@auth'
            - '@pagination'
            - '@ernadoo.phpbbdirectory.core.categorie'
            - '@ernadoo.phpbbdirectory.core.link'

    ernadoo.phpbbdirectory.controller.links:
        class: ernadoo\phpbbdirectory\controller\links
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@request'
            - '@auth'
            - '@captcha.factory'
            - '@ernadoo.phpbbdirectory.core.categorie'
            - '@ernadoo.phpbbdirectory.core.link'
            - '%core.root_path%'
            - '%core.php_ext%'

    ernadoo.phpbbdirectory.controller.comments:
        class: ernadoo\phpbbdirectory\controller\comments
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@request'
            - '@auth'
            - '@pagination'
            - '@captcha.factory'
            - '@ernadoo.phpbbdirectory.core.categorie'
            - '@ernadoo.phpbbdirectory.core.comment'
            - '%core.root_path%'
            - '%core.php_ext%'

    ernadoo.phpbbdirectory.controller.search:
        class: ernadoo\phpbbdirectory\controller\search
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@request'
            - '@auth'
            - '@pagination'
            - '@ernadoo.phpbbdirectory.search.fulltext_directory'
            - '@ernadoo.phpbbdirectory.core.categorie'
            - '@ernadoo.phpbbdirectory.core.link'

    ernadoo.phpbbdirectory.event.listener:
        class: ernadoo\phpbbdirectory\event\listener
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@template'
            - '%core.table_prefix%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    ernadoo.phpbbdirectory.core.categorie:
        class: ernadoo\phpbbdirectory\core\categorie
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@request'
            - '@auth'
            - '@cron.manager'

    ernadoo.phpbbdirectory.core.cron:
        class: ernadoo\phpbbdirectory\core\cron
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@log'
            - '@user'
            - '@notification_manager'
            - '@ernadoo.phpbbdirectory.core.link'
            - '%core.root_path%'
            - '%core.php_ext%'

    ernadoo.phpbbdirectory.core.link:
        class: ernadoo\phpbbdirectory\core\link
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@request'
            - '@auth'
            - '@notification_manager'
            - '@filesystem'
            - '@upload_imagesize'
            - '@files.factory'
            - '%core.root_path%'
            - '%core.php_ext%'

    ernadoo.phpbbdirectory.core.comment:
        class: ernadoo\phpbbdirectory\core\comment
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@dbal.conn'
            - '@language'

    ernadoo.phpbbdirectory.core.helper:
        class: ernadoo\phpbbdirectory\core\helper
        abstract: true
        calls:
            - [set_extension_manager, ['@ext.manager']]
            - [set_path_helper, ['@path_helper']]
            - [set_tables, ['%tables.dir.categories%','%tables.dir.comments%','%tables.dir.links%','%tables.dir.votes%','%tables.dir.watch%']]

    ernadoo.phpbbdirectory.core.nestedset_category:
        class: ernadoo\phpbbdirectory\core\nestedset_category
        arguments:
            - '@dbal.conn'
            - '@ernadoo.phpbbdirectory.table_lock'
            - '%tables.dir.categories%'

    ernadoo.phpbbdirectory.routing.loader:
        class: ernadoo\phpbbdirectory\routing\categories_loader
        arguments:
            - '@dbal.conn'
            - '%tables.dir.categories%'
        tags:
            - { name: routing.loader }

    ernadoo.phpbbdirectory.search.fulltext_directory:
        class: ernadoo\phpbbdirectory\search\fulltext_directory
        parent: ernadoo.phpbbdirectory.core.helper
        arguments:
            - '@dbal.conn'

    ernadoo.phpbbdirectory.table_lock:
        class: phpbb\lock\db
        arguments:
            - ernadoo.phpbbdirectory.table_lock.directory_cats
            - '@config'
            - '@dbal.conn'